apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: todo-gitops-app
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: amadeus-repo
  interval: 1m
  path: ./todo-project/manifests 
  prune: true 
  validation: client 
# Useless comment for pushing